### ISSUE TITLE
Enahncement: Add text window support (VDU 28).

### ISSUE THREAD

**Issue by lennart-benschop** [breakintoprogram/agon-vdp#48] opened 2023-05-07 20:18 UTC
Now that I have implemented MODE7 in my own fork of the VDP, I see that some existing BBC Basic programs put control characters for foreground colour in the left column and then set a text window using VDU28, so these control codes will remain in place. It is also useful for interactively typing plotting commands, so the typed commands remain in a window separate from the graphics being plotted.

Therefore I think that VDU 28 is quite useful. VDU 28, left_column, bottom_row, right_column, top_row.
VDU 24 (graphics window) could also be implemented and of course VDU 26 to reset the windows to their defaults,which is full screen.
VDU24 probably requires some magic with Canvas->setClippingRectangle() to limit the extent of drawn lines to that window.
VDU28 can just be managed inside video.,ino, adding the required offsets and limit checks.

**Comment by lennart-benschop** [comment] 2023-05-08 15:45
One good reason to have this functionality is for having the scroll functionality (VDU 23,7) for just the text window. Being able to scroll just  a section of the screen is a killer feature we must have!

**Comment by leventp** [comment] 2023-05-08 21:38
Issue #29 already opened for this purpose.

**Comment by breakintoprogram** [comment] 2023-05-19 16:38
Closing as it is a duplicate of #29

**Closed by breakintoprogram** 2023-05-19 16:38 UTC
Labels: duplicate
